version: "3.5"

services:
  test:
    image: busybox
    command: cat /app/config.txt
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 * * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
    configs:
      - source: my_config
        target: /app/config.txt

configs:
  my_config:
    file: ./config.txt
